import { api } from './api';
import { Opportunity } from '../types';

export const demoOpportunities: any[] = [
  // --- 10 FRANCHISE OPPORTUNITIES (type: "brand") ---
  {
    brand_name: "Tea Junction – Premium Beverage Outlets",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Chai_Sutta_Bar_Logo.png",
    usp: "Join India's leading beverage chain with a focus on hygiene and standardized operations.",
    category: "Food & Beverage",
    description: "Join a rapidly expanding tea and snacks brand. Proven business model with low entry capital and high customer retention.",
    minInvestment: 1500000,
    maxInvestment: 2500000,
    investment_range: "₹15L – ₹25L",
    space_req: "300 – 500 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1593397486515-562998a44b81?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Pan India",
    trustScore: 92,
    franchiseFee: "₹6L",
    setupCost: "₹10L - ₹15L",
    monthlyRoyalty: "6% of Net Sales",
    trainingDays: 7,
    trainingFor: "Owner & Core Staff",
    marketingSupport: "Social Media Ads + Local Store Launch Event",
    sopManualGiven: true,
    breakEvenMonths: 18,
  },
  {
    brand_name: "Lenskart Eyewear – Retail Partnership",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Lenskart_Logo.svg",
    usp: "India's largest omni-channel eyewear network with multi-city presence.",
    category: "Retail",
    description: "Lead the vision-care sector with an AI-driven retail model. High surgical precision and backend supply chain support.",
    minInvestment: 2500000,
    maxInvestment: 3500000,
    investment_range: "₹25L – ₹35L",
    space_req: "400 – 600 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1511499767390-91f15170b047?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Metro Cities",
    trustScore: 89,
    franchiseFee: "₹10L",
    setupCost: "₹20L",
    monthlyRoyalty: "No Royalty (Profit Sharing on Frames)",
    trainingDays: 14,
    trainingFor: "Staff (Optometrists & Sales)",
    marketingSupport: "National TV Campaigns + Local Search Ads",
    sopManualGiven: true,
    breakEvenMonths: 24,
  },
  {
    brand_name: "Naturals Salon & Wellness Center",
    logo: "https://photos.naturals.in/logo.png",
    usp: "South India's most recognized beauty brand with a focus on female entrepreneurship.",
    category: "Wellness",
    description: "Operate a premium grooming and wellness center under a legacy brand banner.",
    minInvestment: 5000000,
    maxInvestment: 8000000,
    investment_range: "₹50L – ₹80L",
    space_req: "1000 – 1500 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "South India",
    trustScore: 94,
    franchiseFee: "₹15L",
    setupCost: "₹40L+",
    monthlyRoyalty: "10% of Service Sales",
    trainingDays: 30,
    trainingFor: "Staff & Management",
    marketingSupport: "Celebrity Endorsements + Hyperlocal Marketing",
    sopManualGiven: true,
    breakEvenMonths: 30,
  },
  {
    brand_name: "EuroKids – Own a Proven Business",
    logo: "https://www.eurokidsindia.com/assets/images/header-logo.png",
    usp: "Join India's fastest-growing Education chain with 100+ successful outlets.",
    category: "Education",
    description: "Multi-award winning pre-school franchise with edge-certified curriculum.",
    minInvestment: 1200000,
    maxInvestment: 2000000,
    investment_range: "₹12L – ₹20L",
    space_req: "1500 – 2500 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "North India",
    trustScore: 91,
    franchiseFee: "₹6L",
    setupCost: "₹10L (Furniture & Play Area)",
    monthlyRoyalty: "15% of Tuition Fees",
    trainingDays: 10,
    trainingFor: "Teachers & Principal",
    marketingSupport: "Local Newspaper Ads + Parent Counseling Events",
    sopManualGiven: true,
    breakEvenMonths: 15,
  },
  {
    brand_name: "Wellness Mart – Holistic Health Distribution",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/ef/Patanjali_Ayurved_Logo.svg",
    usp: "Join India's fastest-growing Ayurvedic chain with 100+ successful outlets.",
    category: "Wellness",
    description: "The most trusted swadeshi FMCG brand with millions of loyal customers.",
    minInvestment: 500000,
    maxInvestment: 1500000,
    investment_range: "₹5L – ₹15L",
    space_req: "300 – 800 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1615485925600-9723704fc9a9?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Semi Urban",
    trustScore: 88,
    franchiseFee: "No Fee (Inventory based)",
    setupCost: "₹3L - ₹5L (Racks & Branding)",
    monthlyRoyalty: "0%",
    trainingDays: 3,
    trainingFor: "Owner",
    marketingSupport: "Brand Provided Glow-signs + Posters",
    sopManualGiven: true,
    breakEvenMonths: 12,
  },
  {
    brand_name: "Subway – Own a Proven Business",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Subway_2016_logo.svg",
    usp: "Join India's fastest-growing QSR chain with 100+ successful outlets.",
    category: "Food & Beverage",
    description: "Standardized healthy fast food option with globally recognized operating procedures.",
    minInvestment: 3500000,
    maxInvestment: 6000000,
    investment_range: "₹35L – ₹60L",
    space_req: "300 – 800 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "High Streets",
    trustScore: 95,
    franchiseFee: "₹6.5L",
    setupCost: "Hot & Cold Kitchen + Interior",
    monthlyRoyalty: "8% of Weekly Sales",
    trainingDays: 14,
    trainingFor: "Manager & Sandwich Artists",
    marketingSupport: "National Television Ads + App Offers",
    sopManualGiven: true,
    breakEvenMonths: 24,
  },
  {
    brand_name: "DTDC Courier – Own a Proven Business",
    logo: "https://www.dtdc.in/img/logo.png",
    usp: "Join India's fastest-growing Logistics chain with 100+ successful outlets.",
    category: "Logistics",
    description: "Start a courier and cargo agency with one of India's largest shipping networks.",
    minInvestment: 150000,
    maxInvestment: 400000,
    investment_range: "₹1.5L – ₹4L",
    space_req: "150 – 300 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1580674684081-7617fbf391f3?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Neighborhoods",
    trustScore: 87,
    franchiseFee: "₹50,000",
    setupCost: "₹1L (Computer, Scale, Furniture)",
    monthlyRoyalty: "10-20% Commission on Business Done",
    trainingDays: 2,
    trainingFor: "Owner",
    marketingSupport: "Signage + Pamphlets",
    sopManualGiven: true,
    breakEvenMonths: 6,
  },
  {
    brand_name: "Golden Heritage Jewels – Luxury Retail",
    logo: "https://www.kalyanjewellers.net/images/logo.png",
    usp: "Join India's fastest-growing Jewelry chain with 100+ successful outlets.",
    category: "Retail",
    description: "High-trust gold and diamond jewelry retail with legacy branding.",
    minInvestment: 50000000,
    maxInvestment: 100000000,
    investment_range: "₹5Cr – ₹10Cr",
    space_req: "1500 – 3000 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1515562141207-7a88bb7ce338?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Main Market",
    trustScore: 96,
    franchiseFee: "₹50L",
    setupCost: "Stock + Security Systems + High-end Interior",
    monthlyRoyalty: "Management Fee: 2%",
    trainingDays: 21,
    trainingFor: "Staff (Gemologists & Security)",
    marketingSupport: "National Celebrity Events + Prime-time TV",
    sopManualGiven: true,
    breakEvenMonths: 48,
  },
  {
    brand_name: "Urban Dumpling Hub – Asian Fusion QSR",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/f6/Wow%21_Momo_Logo.png",
    usp: "Join India's fastest-growing QSR chain with 100+ successful outlets.",
    category: "Food & Beverage",
    description: "Rapidly growing brand revolutionizing momos with organized kiosks.",
    minInvestment: 1000000,
    maxInvestment: 2500000,
    investment_range: "₹10L – ₹25L",
    space_req: "250 – 500 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c170db76?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Malls, Kiosks",
    trustScore: 90,
    franchiseFee: "₹5L",
    setupCost: "Kiosk Fabricaton + Kitchen",
    monthlyRoyalty: "8% of sales",
    trainingDays: 7,
    trainingFor: "Kitchen & Counter Staff",
    marketingSupport: "In-Mall Branding + Digital Campaign",
    sopManualGiven: true,
    breakEvenMonths: 14,
  },
  {
    brand_name: "Apollo Pharmacy – Own a Proven Business",
    logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/Apollo_Hospitals_Logo.svg",
    usp: "Join India's fastest-growing Healthcare chain with 100+ successful outlets.",
    category: "Healthcare",
    description: "India's largest organized pharmacy chain with a massive inventory system.",
    minInvestment: 1000000,
    maxInvestment: 2000000,
    investment_range: "₹10L – ₹20L",
    space_req: "250 – 500 Sq. Ft.",
    supportDetails: "Full Training + Marketing + Staff Hiring.",
    is_verified: true,
    status: 'verified',
    type: "brand",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Tier 1 & 2",
    trustScore: 93,
    franchiseFee: "₹5L",
    setupCost: "Drug License + HVAC + Interior",
    monthlyRoyalty: "5% of Revenue",
    trainingDays: 5,
    trainingFor: "Pharmacists",
    marketingSupport: "Health Camps + Local Newspaper Insertions",
    sopManualGiven: true,
    breakEvenMonths: 18,
  },

  // --- 10 DEALERSHIP OPPORTUNITIES (type: "dealership") ---
  {
    brand_name: "Authorized Bajaj Electricals Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Bajaj_Group_Logo.svg/1200px-Bajaj_Group_Logo.svg.png",
    usp: "Exclusive rights to sell the latest Bajaj products in your city.",
    category: "Electronics",
    description: "Premium dealer partnership with India's leading consumer durables brand.",
    minInvestment: 1000000,
    maxInvestment: 5000000,
    investment_range: "₹10L – ₹50L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "City Level",
    trustScore: 88,
    heroProducts: [
      { name: "Bajaj Ceiling Fans", image: "https://images.unsplash.com/photo-1591129841117-3adfd313e34f?q=80&w=200" },
      { name: "Bajaj Juicer Mixers", image: "https://images.unsplash.com/photo-1585232004423-244e0e6904e3?q=80&w=200" }
    ],
    marginPerUnitRange: "₹500 to ₹3,500 per unit",
    performanceBonusDetails: "Annual Incentive: Up to ₹5L for meeting T.O. targets",
    afterSalesServiceDetails: "On-site warranty handled directly by Bajaj Authorized Service Centers.",
    showroomLayoutReq: "150 sq ft display area with branded glow-signs."
  },
  {
    brand_name: "Authorized Asian Paints Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Asian_Paints_logo.png",
    usp: "Exclusive rights to sell the latest Decorative Paints in your city.",
    category: "Construction",
    description: "Leading market share in Indian paint industry. Strong brand pull.",
    minInvestment: 800000,
    maxInvestment: 1500000,
    investment_range: "₹8L – ₹15L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "District HQ",
    trustScore: 94,
    heroProducts: [
      { name: "Royale Luxury Emulsion", image: "https://images.unsplash.com/photo-1589939705384-5185138a04b9?q=80&w=200" }
    ],
    marginPerUnitRange: "₹200 to ₹1,200 per can",
    performanceBonusDetails: "Monthly schemes based on volume lifts.",
    afterSalesServiceDetails: "Expert painting service referrals provided to customers.",
    showroomLayoutReq: "Wall-mounted shade cards and color consulting kiosk."
  },
  {
    brand_name: "Authorized Sonalika Tractors Dealership",
    logo: "https://www.sonalika.com/assets/img/logo.png",
    usp: "Exclusive rights to sell the latest Agri Tech products in your city.",
    category: "Automobile",
    description: "Heavy machinery dealership for the booming agricultural sector.",
    minInvestment: 5000000,
    maxInvestment: 15000000,
    investment_range: "₹50L – ₹1.5Cr (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1530268577195-21d782ae3e2a?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Semi-Urban Center",
    trustScore: 86,
    heroProducts: [
        { name: "Tiger Series Tractors", image: "https://images.unsplash.com/photo-1595113316349-9fa4ee24f884?q=80&w=200" }
    ],
    marginPerUnitRange: "₹25,000 to ₹65,000 per tractor",
    performanceBonusDetails: "Quarterly rebates for high volume dealers.",
    afterSalesServiceDetails: "Service workshop required; Spare parts supplied at 80% credit.",
    showroomLayoutReq: "Min 1000 sq ft workshop + 500 sq ft showroom."
  },
  {
    brand_name: "Authorized Philips Lighting Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Philips_logo.svg",
    usp: "Exclusive rights to sell the latest LED Solutions in your city.",
    category: "Electronics",
    description: "Top-tier lighting solutions for residential and commercial projects.",
    minInvestment: 500000,
    maxInvestment: 1200000,
    investment_range: "₹5L – ₹12L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1550985543-f47f38aee65e?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Zonal Level",
    trustScore: 90,
    heroProducts: [
        { name: "Philips Hue Smart LED", image: "https://images.unsplash.com/photo-1550186082-ae9231f2b604?q=80&w=200" }
    ],
    marginPerUnitRange: "₹50 to ₹1,500 per lamp/fitting",
    performanceBonusDetails: "Builder project incentives for bulk supply.",
    afterSalesServiceDetails: "2-year replacement warranty handled by the dealer (Stock refilled).",
    showroomLayoutReq: "Experience center to demo smart lighting."
  },
  {
    brand_name: "Authorized Voltas AC Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Voltas_logo.svg",
    usp: "Exclusive rights to sell the latest Cooling Products in your city.",
    category: "Electronics",
    description: "India's #1 air conditioning brand with high seasonal turnover.",
    minInvestment: 2000000,
    maxInvestment: 4000000,
    investment_range: "₹20L – ₹40L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1631548231167-8d022467d581?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Urban Centers",
    trustScore: 92,
    heroProducts: [
        { name: "Voltas Adjustable Inverter AC", image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=200" }
    ],
    marginPerUnitRange: "₹2,500 to ₹7,000 per AC",
    performanceBonusDetails: "Summer peak performance incentives.",
    afterSalesServiceDetails: "Voltas service franchisee backup provided.",
    showroomLayoutReq: "Wall fixtures for at least 6 display models."
  },
  {
    brand_name: "Authorized Jaquar Bath Dealership",
    logo: "https://www.jaquar.com/skin/frontend/jaquar/default/images/logo.png",
    usp: "Exclusive rights to sell the latest Sanitaryware in your city.",
    category: "Construction",
    description: "Premium bath fittings for the growing real estate market.",
    minInvestment: 3000000,
    maxInvestment: 6000000,
    investment_range: "₹30L – ₹60L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Commercial Hubs",
    trustScore: 93,
    heroProducts: [
        { name: "Jaquar Artize Collection", image: "https://images.unsplash.com/photo-1584132905271-512c858572ea?q=80&w=200" }
    ],
    marginPerUnitRange: "₹1,500 to ₹15,000 per fixture",
    performanceBonusDetails: "Preferred architect connect events.",
    afterSalesServiceDetails: "On-site plumber training provided by brand.",
    showroomLayoutReq: "Luxurious display booths (live water demo preferred)."
  },
  {
    brand_name: "Authorized Hero MotoCorp Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Hero_MotoCorp_Logo.svg",
    usp: "Exclusive rights to sell the latest 2-Wheelers in your city.",
    category: "Automobile",
    description: "Join the world's largest manufacturer of two-wheelers.",
    minInvestment: 10000000,
    maxInvestment: 30000000,
    investment_range: "₹1Cr – ₹3Cr (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Tier 2 & 3",
    trustScore: 95,
    heroProducts: [
        { name: "Hero Splendor +", image: "https://images.unsplash.com/photo-1558981001-5864b22caead?q=80&w=200" }
    ],
    marginPerUnitRange: "₹3,500 to ₹9,000 per bike",
    performanceBonusDetails: "Exchange program subsidies & Festive targets.",
    afterSalesServiceDetails: "Standardized service bays (6+ bays req).",
    showroomLayoutReq: "3S facility (Sales, Service, Spares) of 3000 sq ft."
  },
  {
    brand_name: "Authorized JK Tyre Dealership",
    logo: "https://www.jktyre.com/images/jktyre-logo.png",
    usp: "Exclusive rights to sell the latest Radial Tyres in your city.",
    category: "Automobile",
    description: "Crucial supplier for the transport and private commute sector.",
    minInvestment: 1500000,
    maxInvestment: 3000000,
    investment_range: "₹15L – ₹30L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1549468057-5b7fa1a41d7a?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Highways/Industrial",
    trustScore: 89,
    heroProducts: [
        { name: "JK UX Royale", image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=200" }
    ],
    marginPerUnitRange: "₹300 to ₹3,500 per tyre",
    performanceBonusDetails: "Fleet connect programs and direct supply targets.",
    afterSalesServiceDetails: "Tyre replacement warranty based on tread wear.",
    showroomLayoutReq: "Wheel alignment & balancing machine required."
  },
  {
    brand_name: "Authorized Godrej Interior Dealership",
    logo: "https://www.godrejinterio.com/assets/images/logo.png",
    usp: "Exclusive rights to sell the latest Furniture in your city.",
    category: "Home & Garden",
    description: "Eco-friendly and ergonomically designed furniture with high brand loyalty.",
    minInvestment: 2500000,
    maxInvestment: 5000000,
    investment_range: "₹25L – ₹50L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Retail Streets",
    trustScore: 91,
    heroProducts: [
        { name: "Godrej Slimline Wardrobes", image: "https://images.unsplash.com/photo-1558997519-53bb890929a3?q=80&w=200" }
    ],
    marginPerUnitRange: "₹1,500 to ₹12,000 per unit",
    performanceBonusDetails: "Corporate office supply incentives.",
    afterSalesServiceDetails: "Home installation team training provided.",
    showroomLayoutReq: "Interior design planning software provided."
  },
  {
    brand_name: "Authorized Kent RO Dealership",
    logo: "https://upload.wikimedia.org/wikipedia/en/0/05/Kent_RO_Systems_Logo.svg",
    usp: "Exclusive rights to sell the latest Purifiers in your city.",
    category: "Appliances",
    description: "Market leader in water purification with high recurring service revenue.",
    minInvestment: 500000,
    maxInvestment: 1000000,
    investment_range: "₹5L – ₹10L (Depending on Stock)",
    supportDetails: "Inventory: Direct from Manufacturer.",
    is_verified: true,
    status: 'verified',
    type: "dealership",
    image: "https://images.unsplash.com/photo-1585707348160-2ef8440c9cf1?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Pan India",
    trustScore: 87,
    heroProducts: [
        { name: "Kent Grand Plus", image: "https://images.unsplash.com/photo-1610493863459-7157a55f8842?q=80&w=200" }
    ],
    marginPerUnitRange: "₹1,500 to ₹4,500 per purifier",
    performanceBonusDetails: "AMC subscription commission for the dealer.",
    afterSalesServiceDetails: "Dealer handles AMC; Original spares supplied by Kent.",
    showroomLayoutReq: "Demo counter with running water connection."
  },

  // --- 10 DISTRIBUTION OPPORTUNITIES (type: "distribution") ---
  {
    brand_name: "Regional Distribution: ITC FMCG",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/ITC_Limited_logo.svg/1200px-ITC_Limited_logo.svg.png",
    usp: "Master the supply chain. Be the sole supplier for Regional Areas.",
    category: "FMCG",
    description: "Manage a wide portfolio of products including Aashirvaad, Sunfeast, and Bingo. Warehouse required.",
    minInvestment: 2500000,
    maxInvestment: 10000000,
    investment_range: "₹25L+",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "District Level",
    trustScore: 96,
    territoryDefinition: "North Pune District - Full Coverage",
    existingRetailerCount: 240,
    stockArrivalFrequency: "Bi-weekly via HQ Logistics",
    creditPeriodDays: 14,
    deliveryVansRequired: 2,
    warehouseSqFt: 1500
  },
  {
    brand_name: "Regional Distribution: Amul Dairy",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/f3/Amul_official_logo.svg",
    usp: "Master the supply chain. Be the sole supplier for Zonal Markets.",
    category: "Dairy",
    description: "India's largest food brand distribution with high turnover for dairy products.",
    minInvestment: 1500000,
    maxInvestment: 5000000,
    investment_range: "₹15L – ₹50L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1550583760-b8c677aeb7d7?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Urban Suburbs",
    trustScore: 97,
    territoryDefinition: "South Mumbai - Zonal Coverage",
    existingRetailerCount: 500,
    stockArrivalFrequency: "Daily morning arrival (Cold Chain)",
    creditPeriodDays: 0,
    deliveryVansRequired: 4,
    warehouseSqFt: 800
  },
  {
    brand_name: "Regional Distribution: Coca-Cola",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Coca-Cola_logo.svg",
    usp: "Master the supply chain. Be the sole supplier for City Outskirts.",
    category: "Beverages",
    description: "High-volume logistics and route management for global beverage giant.",
    minInvestment: 4000000,
    maxInvestment: 8000000,
    investment_range: "₹40L – ₹80L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Regional Hubs",
    trustScore: 94,
    territoryDefinition: "Bangalore Rural - High Growth Zone",
    existingRetailerCount: 350,
    stockArrivalFrequency: "Weekly on Fridays",
    creditPeriodDays: 21,
    deliveryVansRequired: 3,
    warehouseSqFt: 3000
  },
  {
    brand_name: "Regional Distribution: Dabur FMCG",
    logo: "https://upload.wikimedia.org/wikipedia/en/0/07/Dabur_Logo.svg",
    usp: "Master the supply chain. Be the sole supplier for Rural Clusters.",
    category: "FMCG",
    description: "Deep penetration into healthcare and homecare products with strong rural demand.",
    minInvestment: 1000000,
    maxInvestment: 2500000,
    investment_range: "₹10L – ₹25L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1582213706041-3bc67cfd89d8?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Village Clusters",
    trustScore: 92,
    territoryDefinition: "Udupi District Rural Cluster",
    existingRetailerCount: 180,
    stockArrivalFrequency: "Bi-weekly",
    creditPeriodDays: 30,
    deliveryVansRequired: 1,
    warehouseSqFt: 1000
  },
  {
    brand_name: "Regional Distribution: Nestle India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Nestl%C3%A9_logo.svg",
    usp: "Master the supply chain. Be the sole supplier for Tech Parks.",
    category: "FMCG",
    description: "Organized supply for Maggi, Nescafé, and confectionery products.",
    minInvestment: 3000000,
    maxInvestment: 7000000,
    investment_range: "₹30L – ₹70L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Urban Centers",
    trustScore: 95,
    territoryDefinition: "Hyderabad IT Corridor",
    existingRetailerCount: 120,
    stockArrivalFrequency: "Weekly",
    creditPeriodDays: 15,
    deliveryVansRequired: 2,
    warehouseSqFt: 1200
  },
  {
    brand_name: "Regional Distribution: HUL Products",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Unilever.svg",
    usp: "Master the supply chain. Be the sole supplier for Smart Cities.",
    category: "FMCG",
    description: "Massive scale distribution for India's largest home and personal care company.",
    minInvestment: 5000000,
    maxInvestment: 15000000,
    investment_range: "₹50L – ₹1.5Cr",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "City Districts",
    trustScore: 98,
    territoryDefinition: "Indore Smart City Zone",
    existingRetailerCount: 650,
    stockArrivalFrequency: "Daily dispatch from C&F",
    creditPeriodDays: 7,
    deliveryVansRequired: 5,
    warehouseSqFt: 4000
  },
  {
    brand_name: "Regional Distribution: Haldiram's Snacks",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fa/Haldiram%27s_Logo.svg/1200px-Haldiram%27s_Logo.svg.png",
    usp: "Master the supply chain. Be the sole supplier for Highway Zones.",
    category: "Food & Beverage",
    description: "High-demand traditional snacks and sweets distribution with stable margins.",
    minInvestment: 2000000,
    maxInvestment: 4500000,
    investment_range: "₹20L – ₹45L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1601050690597-df056fbec7ad?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Highway Centers",
    trustScore: 93,
    territoryDefinition: "NH-48 Jaipur Highway Stretch",
    existingRetailerCount: 150,
    stockArrivalFrequency: "Weekly twice",
    creditPeriodDays: 7,
    deliveryVansRequired: 2,
    warehouseSqFt: 2000
  },
  {
    brand_name: "Regional Distribution: Parle Biscuits",
    logo: "https://www.parleproducts.com/img/parle-logo.png",
    usp: "Master the supply chain. Be the sole supplier for Rural Towns.",
    category: "FMCG",
    description: "Consistent volume distribution for India's favorite biscuits and confectionery.",
    minInvestment: 1200000,
    maxInvestment: 2500000,
    investment_range: "₹12L – ₹25L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1558961359-1d9c79f977c6?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Town Tiers",
    trustScore: 90,
    territoryDefinition: "Guntur Rural Town Cluster",
    existingRetailerCount: 400,
    stockArrivalFrequency: "Daily volume dispatch",
    creditPeriodDays: 7,
    deliveryVansRequired: 3,
    warehouseSqFt: 1500
  },
  {
    brand_name: "Regional Distribution: PepsiCo",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a6/PepsiCo_logo.svg",
    usp: "Master the supply chain. Be the sole supplier for University Zones.",
    category: "FMCG",
    description: "Cold supply chain management for snacks and carbonated soft drinks.",
    minInvestment: 3500000,
    maxInvestment: 7000000,
    investment_range: "₹35L – ₹70L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1543253687-c931c8e01820?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Institutional Hubs",
    trustScore: 91,
    territoryDefinition: "NCR West University Area",
    existingRetailerCount: 80,
    stockArrivalFrequency: "Daily delivery to coolers",
    creditPeriodDays: 14,
    deliveryVansRequired: 2,
    warehouseSqFt: 1200
  },
  {
    brand_name: "Regional Distribution: Pidilite (Fevicol)",
    logo: "https://www.pidilite.com/wp-content/themes/pidilite/assets/images/logo.png",
    usp: "Master the supply chain. Be the sole supplier for Hardware Markets.",
    category: "Industrial",
    description: "Market leader in adhesives and construction chemicals with 0% competition.",
    minInvestment: 1500000,
    maxInvestment: 3000000,
    investment_range: "₹15L – ₹30L",
    supportDetails: "Role: B2B Supply to 200+ Retailers.",
    is_verified: true,
    status: 'verified',
    type: "distribution",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89012e?q=80&w=1600&auto=format&fit=crop",
    owner_uid: "demo-brand-owner",
    location: "Hardware Markets",
    trustScore: 96,
    territoryDefinition: "North Delhi Hardware Hub",
    existingRetailerCount: 300,
    stockArrivalFrequency: "Weekly via factory route",
    creditPeriodDays: 21,
    deliveryVansRequired: 1,
    warehouseSqFt: 800
  }
];

export async function seedDemoData() {
  try {
    const existing = await api.get('/opportunities');
    const list: any[] = existing.opportunities || existing || [];
    if (list.length > 0) return false; // already has data
  } catch (_) {}

  for (const opp of demoOpportunities) {
    try {
      await api.post('/opportunities', opp);
    } catch (_) {}
  }
  return true;
}

export async function clearAndSeedData() {
  // Use the backend reseed endpoint (admin only)
  try {
    await api.post('/opportunities/admin/reseed', {});
    return true;
  } catch (_) {
    return false;
  }
}
